### ISSUE TITLE
Kodi Playlist Card

### ISSUE THREAD

**Issue by fax13** [jtbgroup/kodi-playlist-card#1]
hi there, i installed the media sensor bundle (latest) and except for "Kodi Playlist Card" all works ell.
for the "Kodi Playlist Card" i only get a black small window.

- reinstalled several times
- double checked the config
- what i saw is that the card isn't loading in my frontend (always a circle spinning).
- running on :
Version | core-2021.7.2
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.9.5
Operating System Family | Linux
Operating System Version | 5.9.16

**Comment by jtbgroup** [comment]
Hi, I'm running the same version of HA without problem. Can you check the content of the sensor in the Developer tools (states). When running kodi, the sensor call 'sensor.kodi_media_sensor_playlist' should content data.

**Comment by fax13** [comment]
hi Gautier,
merci for the reply.
i've looked at what you've mentioned and made a cut out of the info.
![Screenshot 2021-07-15 103225](https://user-images.githubusercontent.com/76689575/125756253-747f002b-dfab-46b7-b6f5-f7b6877eec28.png)
i would be so glad this to work because i'm a huge kodi fan and this is a missing link for me and my home assistant.
:-)

**Comment by jtbgroup** [comment]
Ok, let's try to find why you don't get any information.

Was your kodi running a playlist (audio or video) when you took the screenshot?  Here a capture of what I get when my audio playlist is running.

![Screenshot_20210715_200310](https://user-images.githubusercontent.com/10096931/125835969-e2c32010-1020-4a6c-afa5-98b4c3bdd7ec.png)

As you can see, in the 'meta' tag, I have an attribute 'playlist_id' = 0, which means audio playlist. In your case, I see "-1"; this is the value when kodi doesn't play anything.

There is another thing you can try. The integration uses json rpc to query kodi; you can try that kind of query in a browser and enter this URL for example (replace the ***kodi_ip*** by your one; same for the port):

``
http://kodi_ip:8080/jsonrpc?request={%22jsonrpc%22:%222.0%22,%22method%22:%22Player.GetPlayers%22,%22id%22:%221609497939295%22}
``

you should get a json file containing the available players on your kodi.

If that doesn't work, then it's probably a config problem on your kodi.

**Comment by fax13** [comment]
hi Gautier,
i did as requested and i get this error;

"{"error":{"code":-32700,"message":"Parse
error."},"id":"1609497939295","jsonrpc":"2.0"}"

I used the ip address and even changed the port nr.
the port was 8080and i used my assistant one which ends on 8123 both didn't
work.
Next step?
aerts francis.

Op do 15 jul. 2021 om 20:20 schreef Gautier Vanderslyen <
***@***.***>:

**Comment by jtbgroup** [comment]
Maybe the url encoding causes the problem in the request (%22).
Can you try this one ? 
```
http://192.168.1.12:8080/jsonrpc?request={"jsonrpc":"2.0","method":"Player.GetPlayers","id":"1609497939295"} 
```

My kodi IP is 192.168.1.12 and runs on port 8080. Port 8123 is the default port for Home assistant; pay attention not to try to connect to HA, but to Kodi.

Did you try the 'search card' ? [https://github.com/jtbgroup/kodi-search-card](url) If yes, does it work?

You could also try this card [https://github.com/custom-cards/upcoming-media-card](url) as it is based on the same principle. Configuration of this card is done like this:
```
- type: custom:upcoming-media-card
  entity: sensor.kodi_recently_added_tv
  title: Recently Added Episodes
  image_style: fanart
```

**Comment by fax13** [comment]
hey Gautier,
ik vermoed dat je nederlandstalig bent aan je achternaam te zien.
of ik moet mij vergissen.
wel, ik kreeg dit als response met je url;

{"id":"1609497939295","jsonrpc":"2.0","result":[{"name":"VideoPlayer","playsaudio":true,"playsvideo":true,"type":"video"},{"name":"PAPlayer","playsaudio":true,"playsvideo":false,"type":"music"},{"name":"STR-DN840
4A62F6","playsaudio":true,"playsvideo":true,"type":"remote"}]}


de upcoming media card werkt, ik kan de episodes of film lijst zien,
niet bedienen.

de "media search card" is visueel maar doet geen search wanneer ik iets zoek.


Op vr 16 jul. 2021 om 09:44 schreef Gautier Vanderslyen <
***@***.***>:

**Comment by jtbgroup** [comment]
Dag Francis,

Franstalig, maar Nederlands is zeker geen proleem 

Je kodi reageert dus goed op Json queries. Toch raar dat er niets gebeurt. Heb je iets zien passeren in de log files? (supervisor > log provider - core)?

We kunnen ook de intragratie proberen:
1. in the developer tool, switch in yaml mode en tijp

```
service: kodi_media_sensors.call_method
entity_id: sensor.kodi_media_sensor_search
data:
  entity_id: sensor.kodi_media_sensor_search
  method: search
  item:
    media_type: all
    value: beatles
```
en click op call service, zoals hier 
![Screenshot_20210716_123750](https://user-images.githubusercontent.com/10096931/125935606-f9a8e6bd-89aa-4dab-9136-99ae2d232f72.png)

2. open de tab states van de developer tools en zoek op de search sensor. Die zou moeten ingevuld worden met het resultaat zoals hier:

![Screenshot_20210716_124142](https://user-images.githubusercontent.com/10096931/125935868-04ba658b-e52c-4e34-9c53-a19e3d4fbf19.png)

Kijk ook in de logfile op dat moment.

Als er geen resultaat komt dan is er een probleem met de integratie.

Gautier

**Comment by fax13** [comment]
hi Gautier,
the call service geeft dit weer;

2021-07-16 15:23:57 ERROR (MainThread)
[homeassistant.helpers.script.websocket_api_script] websocket_api
script: Error executing script. Invalid data for call_service at pos
1: required key not provided @ data['method']


Op vr 16 jul. 2021 om 12:44 schreef Gautier Vanderslyen <
***@***.***>:

**Comment by fax13** [comment]
hey gautier,
ik was wat aan het neuzen in de logs en kwam dit tegen.
ps: ben maar net sinds een 3tal maanden met HA begonnen, new kid on the
block :)

2021-07-16 16:00:10 ERROR (MainThread)
[custom_components.kodi_media_sensors.entity_kodi_playlist] Error
updating sensor, is kodi running?
Traceback (most recent call last):
  File "/config/custom_components/kodi_media_sensors/entity_kodi_playlist.py",
line 147, in update_meta
    current = playing["id"]
KeyError: 'id'2021-07-16 16:00:10 ERROR (MainThread)
[homeassistant.components.sensor] kodi_media_sensors: Error on device
update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 432, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line
601, in async_device_update
    await task
  File "/config/custom_components/kodi_media_sensors/entity_kodi_playlist.py",
line 93, in async_update
    card_json = self.format_items(result)
  File "/config/custom_components/kodi_media_sensors/entity_kodi_playlist.py",
line 164, in format_items
    "id": item["id"],
KeyError: 'id'


Op vr 16 jul. 2021 om 17:27 schreef Fax-Art ***@***.***>:

**Comment by jtbgroup** [comment]
mmmmmm..... ik zie dat ik het probleem ook heb als ik een film draait op kodi !!!!! :-(

Ik gebruik mijn kodi vooral om naar musiek te luisteren en daar geeft het geen probleem (bij mij, minstens)
als je musiek bestanden heb, kan je eventueel proberen? 

Ik zal dit weekend kijken waarom het niet lukt voor videos.

**Comment by fax13** [comment]
mijn kodi zelf werkt feilloos. alleen de playlist functie en de search issue op HA is mijn probleem. kijk er naar uit om een oplossing te vinden. indien je nog info nodig hebt laat het maar  weten. ;)

**Comment by jtbgroup** [comment]
Ik heb het probleem bij mij kunnen identificeren en oplossen zonder code aanpassing. Voor weet ik welke reden was mijn Video Library niet goed gebouwd en de filmen hadden geen 'id'. Dit is niet normaal en van daar de foutmelding. De 'Upcoming media' kaart maakt geen gebruik van de 'id'; van daar dat die probleem geeft.
 
Wat ik gedaan heb is de library volledig verwijderen (ook alle gegevens van kodi) en opnieuw bouwen. Afhankelijk van je bibliotheek kan het snel gaan (bij mij was het een paar minuten).

Om dit te testen, kan het volgende doen:
1. start een film op kodi (die niet in the playlist card kwam)

2. open je browser en tip
```
http://192.168.1.12:8080/jsonrpc?request={"jsonrpc":"2.0","method":"Playlist.GetItems","id":"1609497939295","params":{"playlistid":1,"properties":["title","thumbnail","file","artist","genre","year","rating","album","track","duration","playcount","dateadded","episode","artistid","albumid","tvshowid"],"limits":{"start":0}}}
```
je zou een json bestand moeten krijgen. Kijk als je een 'ID' hebt voor je item. Firefox is hier handig want we zie de json in een leesbare formaat.
![Screenshot_20210717_055401](https://user-images.githubusercontent.com/10096931/126024757-b448dfa9-2958-435b-9ac6-91dd5add4e8a.png)
Btw, "type" moet ook 'movie' zijn. By mij was het ook leeg voor de manipulatie.

3. Als je dezelfde symptomen heb kan je een rebuild proberen van je bibliotheek.

**Comment by fax13** [comment]
strange, ik heb nooit een library aangemaakt, misschien was dat dan mijn probleem.
op kodi zijn mijn bibs geklasseerd. moet deze aangelegd worden via HA?
alleen de media sensor en recently added  integrations zijn geinstalleerd, moet ik deze verwijderen en terug installeren?

**Comment by fax13** [comment]
oops, dus duidelijk dat ik dat niet heb aangemaakt. ik ga proberen uit te zoeken how dat in zijn werk gaat. mijn films staan op mijn netgear nas en moet uitdokteren hoe ik mijn bibs link met HA. dan zal alles vermoedelijk beter lopen als HA op zijn minst kan zien waar mijn media zich bevind. tenzij ik op het verkeerde spoor ben.

**Comment by fax13** [comment]
speel jij je media lokaal of via een nas of extern?
mijn bibs zijn te groot om lokaal op te slaan (2terra)
dit is mijn opstelling nu;
media_source:
   media: http://192.168.1.172/movies/
   music: http://192.168.1.244/netgear/music
als ik dit in orde krijg zullen de apps wel werken.
:)

**Comment by jtbgroup** [comment]
Ik heb ook alles op een externe NAS. In Kodi voeg ik de verschillende bronnen toe en dan doe in een scan van de bronnen; die komen dan automatisch in je bibilotheek.

[https://kodi.wiki/view/Adding_video_sources](https://kodi.wiki/view/Adding_video_sources)

In HA moet je niet veel doen. Enkel zeker zijn dat de integratie met Kodi in orde is (dat kan je bevestigen met de media player), de Kodi Media Sensors en de kaarten installeren, maar dit heb je allemaal gedaan.

Ik zie 2 verschillende IP's voor je media en voor je musiek ? alles draait dan niet op je nas?

**Comment by fax13** [comment]
in kodi heb ik alles toegevoegd audio en video en speelt voortreffelijk.
ik vermoed dat het de juiste configuratie maken met HA, ik zou mijn databasen met HA moeten kunnen koppelen?
2 ip's zijn 1 nas voor mijn video's en 1 nas voor mijn audio, heb gigantische bibliotheken

**Comment by jtbgroup** [comment]
nee, je moet de database van Kodi niet koppelen met HA.  HA dient enkel als interface voor kodi, maar het is wel Kodi die nog altijd draait.

Heb je deze kunnen testen?
```
http://192.168.1.12:8080/jsonrpc?request={"jsonrpc":"2.0","method":"Playlist.GetItems","id":"1609497939295","params":{"playlistid":1,"properties":["title","thumbnail","file","artist","genre","year","rating","album","track","duration","playcount","dateadded","episode","artistid","albumid","tvshowid"],"limits":{"start":0}}}
```

**Comment by fax13** [comment]
ik krijg dit als respons;
{"id":"1609497939295","jsonrpc":"2.0","result":{"items":[],"limits":{"end":0,"start":0,"total":0}}}
wat ik ook heb ontdekt is dat mijn film nas nog op smb v1 draait en kodi smb ziet dat niet.
werkt alleen vanaf smb v2, dus video gaat op de moment niet.
:(
zo dan kan ik mij concentreren op de muziek en playlists

**Comment by jtbgroup** [comment]
Ok, dan is dit  logisch. Kodi kan niet aan je films en stuurt dan een antwoord zonder item in de playlist 'Movie' ("playlistid":1).
Persoonlijk gebruik ik NFS want SMB was bij mij te traag. 

Nu voor musiek kan je dezelfde oefening doen? (maar nu met "playlist":0). Je laat Kodi spelen en in je browser:
```
http://192.168.1.12:8080/jsonrpc?request={"jsonrpc":"2.0","method":"Playlist.GetItems","id":"1609497939295","params":{"playlistid":0,"properties":["title","thumbnail","file","artist","genre","year","rating","album","track","duration","playcount","dateadded","episode","artistid","albumid","tvshowid"],"limits":{"start":0}}}
```
De bedoeling is hier om zeker te zijn dat Kodi een 'ID' toont voor elke nummer in je playlist.

**Comment by fax13** [comment]
ik zie alle speellijsten met id nummers erin

**Comment by jtbgroup** [comment]
Wel... niet gemakkelijk... Kodi lijkt in orde te zijn.

In HA, je kan nog de developer tool proberen:
1. laat kodi musiek spelen
2. in HA, open 2 vensters met Dev tools: een op 'Services', een op 'events'
3. in Events, in 'events to subcribe to', tijp ***kodi_call_method_result*** + start listening
4. in Services, doe deze (+ call service). Pas de entity id aan natuurlijk
![1](https://user-images.githubusercontent.com/10096931/126045498-39ba196d-8ac0-422d-863b-a810f8c436c7.png)
5. ga terug in Events en kijk als je iets gekregen heb, zoals dit
![2](https://user-images.githubusercontent.com/10096931/126045511-1bbc90b9-580d-48ee-aa50-247630ce537d.png)
zie je de id ook?

Als ja, dan kunnen we terug de call_method van de media sensors proberen.

**Comment by fax13** [comment]
Hi Gautier,
excuses voor mijn afwezigheid. moest weer naar hey buitenland voor mijn werk.
ik heb geprobeerd wat je laatst schreef en heb gezien dat ik alleen ID heb voor een playlist maar niet voor de muziek nrs op zich.

{"id":"1609497939295","jsonrpc":"2.0","result":{"items":[{"file":"smb://192.168.1.244/media/Music amazon playlists/super list 2019/04 Rez.mp3","label":"04. Underworld - Rez","thumbnail":"","title":"","type":"unknown"},{"file":"smb://192.168.1.244/media/Music amazon playlists/super list 2019/Compulsion.mp3","label":"01. Orphx - enz.....
DEV instelling is 
![image](https://user-images.githubusercontent.com/76689575/127770887-898eb3b9-57db-4bf6-b372-65325a0fa365.png)

maar geen event actief of zichtbaar na het activeren van call service

**Comment by fax13** [comment]
oops, hebbes!
call service/event succesvol
Event 1 fired 14:35:
{
    "event_type": "kodi_call_method_result",
    "data": {
        "entity_id": "media_player.android_6",
        "result": {
            "code": -32602,
            "data": {
                "method": "Playlist.GetItems",
                "stack": {
                    "message": "Value between 0 (inclusive) and 2 (inclusive) expected but 2147483647 received",
                    "name": "playlistid",
                    "type": "integer"
                }
            },
            "message": "Invalid params."
        },
        "result_ok": false,
        "input": {
            "method": "Playlist.Getitems",
            "params": {
                "playlistid": 1609497939295,
                "properties": [
                    "title"
                ],
                "limits": {
                    "start": 0
                }
            }
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-08-01T12:35:44.499645+00:00",
    "context": {
        "id": "ae52d3c80a41272d59a3afde5fea0bd3",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 14:34:
{
    "event_type": "kodi_call_method_result",
    "data": {
        "entity_id": "media_player.android_6",
        "result": {
            "code": -32602,
            "data": {
                "method": "Playlist.GetItems",
                "stack": {
                    "message": "Value between 0 (inclusive) and 2 (inclusive) expected but 2147483647 received",
                    "name": "playlistid",
                    "type": "integer"
                }
            },
            "message": "Invalid params."
        },
        "result_ok": false,
        "input": {
            "method": "Playlist.Getitems",
            "params": {
                "playlistid": 1609497939295,
                "properties": [
                    "title"
                ],
                "limits": {
                    "start": 0
                }
            }
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-08-01T12:34:56.154381+00:00",
    "context": {
        "id": "79a6244bf1543d03ee6e852421a2692d",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by fax13** [comment]
playlist nummer vergeten toe te voegen :(

**Comment by jtbgroup** [comment]
Dag Francis,

Voor wat ik zie heb je playlistid nr "1609497939295" toegevoegd, maar dit kan niet (van daar de foutmelding 
**message": "Value between 0 (inclusive) and 2 (inclusive) expected but 2147483647 received",**

1609497939295 is niet de ID van de playlist maar van de json-rpc request.

playlistid is 0 voor audio en 1 voor video. Als je musiek speelt moet je de query uitvoeren met parameter 0 (en 1 voor video)

In de screenshot van vandaag (Dev scherm) zijn de parameters denk ik correct, behalve mischien de entity_id: media_player.**xenon** terwijl in de events zie ik media_player.**android_6** ?

Voor wat ik zie ontbreekt er toch de ID's, en **type":"unknown"** vind ik ook raar voor een .mp3. Hoe gebruik je kodi en de playlist? gebruik je iets zoals .m3u bestanden? Om zeker te zijn dat je bibliotheek vol is kan dat via de chorus interface zien (meestal http://IP_VAN_KODI:8080). Daar moet je de nummers terug vinden (en niet een file structuur). Hoe ziet het eruit bij jou?

**Comment by fax13** [comment]
Hi Gautier,
heb nu well degelijk een event van wat ik aan't spelen ben op mijn kodi.
![image](https://user-images.githubusercontent.com/76689575/127781220-35cad19f-0a2b-4df2-8ddb-96d5c8984c2d.png)

ik heb de ID op 0 gezet en had dit resultaat; (cut out)
![image](https://user-images.githubusercontent.com/76689575/127781232-80035f92-ed48-4150-b9dd-4b3078e43ad4.png)
so far so good. :)

**Comment by jtbgroup** [comment]
Hello,

Al beter :-). Maar je hebt nog geen ID. Ik denk (maar zonder zekerheid) dat die komt wanneer je een crawl doet van de bronnen. Hoe start je je musiek? welke type bestand? vanuit de bibliotheek van kodi? want het lijkt niet het geval te zijn. Wat ik gezien heb laat me denken dat je navigeert via kodi tot een bepaalde folder en dat je dan leest alle bestanden van die folder.

Dit kan natuurlijk ook , maar is niet de bedoeling van een media center en mijn integratie werkt ook nit voor deze use case. Misschien moet ik dat ook dekken, maar niet op korte termijn.

**Comment by fax13** [comment]
ca va, no worries then
ik zal dan deze instelling dan afwachten tot een update.
;)
maar mercie voor je ondersteuning, was zeer leerrijk.

**Comment by jtbgroup** [comment]
hello,
Ik heb een nieuwe versie gepubliceerd. Heb je nog problemen?

**Comment by fax13** [comment]
Hi Gauthier,
Ben even aant reizen voor mijn werk.
Zodra ik terug ben zal ik eens proberen

**Comment by jtbgroup** [comment]
hallo,

heb je de laatste versies kunnen testen?

**Comment by fax13** [comment]
Hi Gauthier, ik ga maandag mijn ha updaten en dan concentreren op mijn plex
integratie. Ben wat aan het uitzoeken plex server goed te laten werken,
eens dat stabiel is kan ik mij op je toepassing focussen. :)

**Comment by fax13** [comment]
Hoi, je cards zijn geinstalleerd en werkt. 😀 als ik Via mijn kodi webadres
bedien zie ik wijzigingen wanneer ik muziek afspeel. De lijst word geupdate
en is zichtbaar. Kodi search en recently added werken ook. 🥳
Alleen kan ik niet een lijst zien of maken met een overzicht van mijn
speellijsten die ik in kodi heb zitten.
Zodat ik die direct kan kiezen zoals in een favorieten lijst bijvoorbeeld.
Of verwacht ik wat veel🤔
Ook merk ik dat kodi regelmatig crashed, dit ga ik vandaag eens uitvissen
waarom, en verder testen van je app.
Good work and keep it up👍

**Comment by jtbgroup** [comment]
De search card is (volgens mij) niet bedoeld om de playlist op te zoeken. Dit zou mogen, maar zou het nut niet echt begrijpen want zoals ik de playlist gebruik heb ik een beperkte aantal speellijsten.

Ik start ze zo via een script:

```
start_kodi_playlist_quiet:
  alias: ''
  sequence:
    - alias: 'Playlist Quiet'
      data:
        entity_id: !secret GLOB_ENTITY_NAME_KODI
        method: Player.Open
        item: {"partymode": "special://profile/playlists/music/Playlist Quiet.xsp"}
      service: kodi.call_method
```

Met deze zou je een caart kunnen maken met eenvoudige knoppen die je script oproept.

**Comment by fax13** [comment]
Hi Gauthier,  so far so good! 👍alleen een playlist die je kan scrollen zo
een kers op de  taart zijn. Lange speellijsten vergroten je view.of heb ik
iets gemist in de settings? 🤷‍♂️

**Comment by jtbgroup** [comment]
ik heb een nieuwe issue gemaakt voor deze: https://github.com/jtbgroup/kodi-playlist-card/issues/3
Niet zeker hoe ik dit moet behandelen in de code... ik zal het bekijken, maar niet onmiddelijk ;-)
