### ISSUE TITLE
Card not showing

### ISSUE THREAD

**Issue by Firesphere** [jtbgroup/kodi-playlist-card#2]
The card is not showing up anymore in Lovelace

Latest HomeAssistant & LibreELEC versions

I only just noticed, but I assume it has to do with one of the latest updates? I can't find anything in the logs about it

**Comment by jtbgroup** [comment]
Hi,

I also run HA core-2021.11.2, Kodi 19 (usin Libreelec too) and I have no problem. Are you running kodi-playlist-card v3.2.0 and kodi-media-sensors v3.1.5?

I know some people had to wait about 20min after updating kodi-media-sensors before having data. Probably some cache on HA, but I don't get why... 

I'll update HA to core-2021.11.3 and check if still no problem

**Comment by Firesphere** [comment]
Hi,

Yes, core-2021.11.2, using LibreELEC 10.0.1, kodi-playlist-card 3.2.0 and kodi-media-sensors 3.1.5

The preview in "select a card" is also blank, which used to be a functional preview.

My Kodi instances are showing up in the integrations list just fine, and when I look at the status, they report the correct status in the integrations from HA, but the card is still not showing.

**Comment by jtbgroup** [comment]
Hello,

can you check in a browser, using the developer mode (F12 in Firefox) and see if you have an error in the console or if something is not loading in the Network tab? Javascript errors will prompt somewhere here.

You can also send me a screenshot of the content of the sensor so I can have a look and see if I find something unusual.

**Comment by Firesphere** [comment]
![image](https://user-images.githubusercontent.com/680570/141945744-dc017611-78bc-48d3-8f1c-c56db2675adc.png)
That's with dev-tools open, refresh.

If I refresh a not-media-card tab, and then go to the tab, it stays blank with this error:
```
21:08:36.887 Uncaught (in promise) DOMException: CustomElementRegistry.define: 'mwc-linear-progress' has already been defined as a custom element app.a6e743b8.js:1243
    i app.a6e743b8.js:1243
    i app.a6e743b8.js:1243
    a typography.js:181
    62744 mwc-linear-progress-base.ts:125
    u app.a6e743b8.js:1243
    13525 e5714b15.js:1
    u app.a6e743b8.js:1243
    u self-hosted:1225
    (Async: promise callback)
    control 9e928c36.js:534
    d 9e928c36.js:534
    c 9e928c36.js:534
    b 9e928c36.js:534
    value c6a59c92.js:144
    _cards c6a59c92.js:144
    map self-hosted:224
    value c6a59c92.js:144
    value c6a59c92.js:144
    value c6a59c92.js:144
    performUpdate app.a6e743b8.js:1243
    scheduleUpdate app.a6e743b8.js:1243
    _$EC app.a6e743b8.js:1243
    AsyncFunctionNext self-hosted:695
    (Async: async)
    requestUpdate app.a6e743b8.js:1243
    o app.a6e743b8.js:1243
    m app.a6e743b8.js:1243
    i c6a59c92.js:144
    value 49692db7.js:409
    value 49692db7.js:409
    (Async: setTimeout handler)
    i ed7c25f5.js:1
    requestAnimationFrame 5180cdb1.js:1
    (Async: FrameRequestCallback)
    requestAnimationFrame 5180cdb1.js:1
    i ed7c25f5.js:1
    value 49692db7.js:409
    _$AE app.a6e743b8.js:1243
    performUpdate app.a6e743b8.js:1243
    scheduleUpdate app.a6e743b8.js:1243
    _$EC app.a6e743b8.js:1243
    AsyncFunctionNext self-hosted:695
    (Async: async)
    requestUpdate app.a6e743b8.js:1243
    set app.a6e743b8.js:1243
    k app.a6e743b8.js:1243
    _$AI app.a6e743b8.js:1243
    m app.a6e743b8.js:1243
    T app.a6e743b8.js:1243
    _$AI app.a6e743b8.js:1243
    S app.a6e743b8.js:1243
    update app.a6e743b8.js:1243
    performUpdate app.a6e743b8.js:1243
    scheduleUpdate app.a6e743b8.js:1243
    _$EC app.a6e743b8.js:1243
    AsyncFunctionNext self-hosted:695
    (Async: async)
    requestUpdate app.a6e743b8.js:1243
    set app.a6e743b8.js:1243
    value app-drawer-layout.js:189
    value hass-loading-screen.ts:11
    performUpdate app.a6e743b8.js:1243
    scheduleUpdate app.a6e743b8.js:1243
    _$EC app.a6e743b8.js:1243
    AsyncFunctionNext self-hosted:695
    (Async: async)
    requestUpdate app.a6e743b8.js:1243
    set app.a6e743b8.js:1243
    k app.a6e743b8.js:1243
    _$AI app.a6e743b8.js:1243
    m app.a6e743b8.js:1243
    T app.a6e743b8.js:1243
    _$AI app.a6e743b8.js:1243
    S app.a6e743b8.js:1243
    update app.a6e743b8.js:1243
```

That sorta narrows it down to the card not being loaded properly when HASS is loaded without that tab active

**Comment by jtbgroup** [comment]
This is really strange. The thing is that I don't use mwc-linear-progress. I wonder if it doesn't come from the mini-player? 
Can you create a complete new page in HA and add only the kodi-playlist-card? And if you didn't before, maybe a clear of your cache?

**Comment by Firesphere** [comment]
I've completely removed the tab, upgraded HA again (as there was an update), reinstalled the card... It's working now.

I have done this two or three times without any luck, but it seems this time it is working again. Closing for now.

**Comment by jtbgroup** [comment]
Well, that's strange!!!! 
But it's good to hear it works again. Thank you for the feedback!
